app/Http/Controllers/AdminController.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/IndexController.php
app/Http/Controllers/SiteController.php
app/Providers/EventServiceProvider.php
config/adminlte.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2018_03_14_182323_create_sites_table.php
resources/views/index.blade.php
resources/views/vendor/adminlte/page.blade.php
routes/web.php

Commitando tudo o que eu fiz

---

app/Http/Controllers/SiteController.php

Exibindo apenas os sites do owner

---

app/Http/Controllers/AdminController.php
config/adminlte.php
resources/views/admin/lista-todos-sites.blade.php
routes/web.php

Issue 14 - exibindo site habilitado/desabilitado

---

app/Http/Controllers/AdminController.php
resources/views/admin/lista-sites.blade.php
resources/views/admin/lista-todos-sites.blade.php
routes/web.php

Implementando desabilitar, habilitar e deletar site

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/SiteController.php
resources/views/admin/lista-todos-sites.blade.php
routes/web.php

Implementando clonar site

---

app/Http/Controllers/SiteController.php
app/Jobs/criaSiteAegir.php

Issue36 Definindo variável do site criado

---

resources/views/sites/create.blade.php
resources/views/sites/edit.blade.php
resources/views/sites/show.blade.php

Estendendo master.blade nas views

---

app/Http/Controllers/SiteController.php

Issue26 NUSPs com permissão de administração

---

app/Http/Controllers/AdminController.php
app/Jobs/clonaSiteAegir.php
app/Jobs/deletaSiteAegir.php
app/Jobs/desabilitaSiteAegir.php
app/Jobs/habilitaSiteAegir.php

Implementados jobs para funções com sites.

---

resources/views/admin/lista-todos-sites.blade.php
resources/views/sites/create.blade.php
resources/views/sites/edit.blade.php
resources/views/sites/index.blade.php
resources/views/sites/show.blade.php

Aplicadas classes Bootstrap.

---

app/Http/Controllers/AdminController.php
resources/views/admin/lista-todos-sites.blade.php

Unificação das opções de consulta do Admin

---

app/Http/Controllers/SiteController.php
resources/views/sites/changeowner.blade.php
resources/views/sites/index.blade.php
routes/web.php

CRUD transferência de responsabilidade do site

---

.gitignore
app/Aegir/Aegir.php
app/Http/Controllers/SiteController.php
app/Policies/SitePolicy.php
app/Providers/AppServiceProvider.php
config/adminlte.php
resources/views/sites/index.blade.php

Implementa sistemas de permissão

---

app/Http/Controllers/SiteController.php
app/Rules/Numeros_USP.php

Validando Responsável e Número USP como inteiro

---

app/Aviso.php
app/Http/Controllers/AvisoController.php
app/Http/Requests/AvisoRequest.php
config/laravel-usp-theme.php
database/factories/AvisoFactory.php
database/factories/SiteFactory.php
database/migrations/2020_07_08_220407_create_avisos_table.php
database/seeds/AvisoSeeder.php
resources/views/avisos/create.blade.php
resources/views/avisos/edit.blade.php
resources/views/avisos/form.blade.php
resources/views/avisos/index.blade.php
resources/views/avisos/show.blade.php
routes/web.php

CRUD de Avisos

---

app/Http/Controllers/SiteController.php
app/Mail/TrocaResponsavelMail.php
resources/views/emails/troca_responsavel.blade.php

Enviar e-mail quando o responsável é trocado

---

app/Http/Controllers/SiteController.php
resources/views/sites/partials/site.blade.php

Opção para voltar status do site para Solicitado.

---

app/Mail/TrocaResponsavelMail.php
resources/views/emails/troca_responsavel.blade.php

Inserido NUSP no e-mail de mudança do responsável

---

app/Http/Controllers/SiteController.php
app/Mail/DeletaAdminMail.php
app/Mail/NovoAdminMail.php
resources/views/emails/deleta_admin.blade.php
resources/views/emails/novo_admin.blade.php
resources/views/emails/troca_responsavel.blade.php

Envia email qdo adicionado/removido administrador

---

app/Http/Controllers/SiteController.php
resources/views/sites/partials/site.blade.php

Habilitar botão Deletar site com status Solicitado

---

app/Mail/AprovaSiteMail.php
app/Mail/DeletaAdminMail.php
app/Mail/NovoAdminMail.php
app/Mail/TrocaResponsavelMail.php
resources/views/emails/aprova_site.blade.php
resources/views/emails/deleta_admin.blade.php
resources/views/emails/novo_admin.blade.php
resources/views/emails/troca_responsavel.blade.php

Configurado pra enviar email qdo usuário existir

---

app/Http/Controllers/ChamadoController.php
app/Models/Chamado.php
config/laravel-usp-theme.php
resources/views/chamados/abertos.blade.php
resources/views/chamados/partials/index.blade.php
routes/web.php

Olá, fiz um esboço da resolução da issue. 
O Filtro para Chamados abertos/fechados recebe informações de váriaveis diferentes pelo que vi ($status e a outra $fechado_em), assim não sei se dá pra implementar a busca da forma que fiz.. 
Sei que quanto mais enxugado ficar o Controller, melhor. Então estou pensando em criar outra variável no Model Chamado integrando o $status e o $fechado_em, dessa forma talvez fique mais fácil de lidar com a busca e com o select na view.
Att, Laura

Campo de Busca e Filtro
